### ISSUE TITLE
adblock: TypeError result[0].trim is not a function

### ISSUE THREAD

**Issue by u8wdz7** [openwrt/packages#11879]
Maintainer: Stan Grishin <stangri@melmac.net>
Environment: ARMv7 Processor rev 0 (v7l), TP-Link Archer C2600, OpenWrt 19.07.2 r10947

Description: After installation the luci console shows the below error message at the Services->Adblock->Overview menu and nod loading anything:
TypeError
result[0].trim is not a function

![image](https://user-images.githubusercontent.com/58440083/79638294-128bb280-8185-11ea-9741-fd5e88e5e223.png)

**Comment by dibdot** [comment]
You've installed adblock ... to fix the above error just update your local package repo (opkg update) and install the updated adblock & luci-app-adblock packages.

**Comment by Lu5ck** [comment]
> You've installed adblock ... to fix the above error just update your local package repo (opkg update) and install the updated adblock & luci-app-adblock packages.

That doesn't fix it. I already install the latest adblock and luci shown in the list.

**Comment by u8wdz7** [comment]
Restart solved the issue for me.

**Comment by NatoBoram** [comment]
I've got the same error.


```yaml
OS: OpenWrt 19.07.2 armv7l
Host: Linksys WRT3200ACM
Kernel: 4.14.171
Uptime: 18 mins
Packages: 179 (opkg)
Shell: ash
Terminal: /dev/pts/0
CPU: Marvell Armada 380/385 (Device Tree) (2)
Memory: 181MiB / 499MiB
```

> Package adblock (4.0.4-4) installed in root is up to date.
> Package luci-app-adblock (git-20.105.64099-eeba108-1) installed in root is up to date.
