### ISSUE TITLE
unbound: allow forwarding to localhost without setting dns_assist

### ISSUE THREAD

**Issue by alaviss** [openwrt/packages#13178]
Maintainer: @EricLuehrsen 
Environment: OpenWrt master

Description:
With the introduction of `dns_assist` from https://github.com/openwrt/packages/commit/e81529596df88eae272c00bf8ac69b15e19a5bd5, unbound init script "helpfully" translated this:

```
config zone
	option enabled '1'
	option fallback '1'
	option zone_type 'forward_zone'
	list server '127.0.0.1@5053'
	list server '127.0.0.1@5054'
	list server '127.0.0.1@5055'
	list server '127.0.0.1@5056'
	list server '127.0.0.1@5057'
	list zone_name '.'
```

into:

```
forward-zone:
  name: .
  forward-host: 127.0.0.1@5053
  forward-host: 127.0.0.1@5054
  forward-host: 127.0.0.1@5055
  forward-host: 127.0.0.1@5056
  forward-host: 127.0.0.1@5057
  forward-first: yes
  forward-tls-upstream: no
```

When `dns_assist` is undefined, which is completely wrong (`forward-host` should be `forward-addr`) and breaks forwarding to `https-dns-proxy`, trashing my router DNS. An option to override this "smart" feature is very much needed.

The walkaround right now is to override the fallback `dns_ast=0` to `dns_ast=1` here:

https://github.com/openwrt/packages/blob/95362efd29cef6433c820fd15bf33e73637a336c/net/unbound/files/unbound.sh#L479-L482
