### ISSUE TITLE
unbound-control failure

### ISSUE THREAD

**Issue by K2DLS** [openwrt/packages#6656]
unbound-control status
[1533215996] unbound-control[14993:0] warning: control-enable is 'no' in the config file.
[1533215996] unbound-control[14993:0] fatal error: could not send: Connection reset by peer

However, config file shows:
option unbound_control '2'

Also tried set to '1'.

Components installed:

libunbound 1.7.3-2
luci-app-unbound git-18.213.60274-7d69fa6-1
unbound 1.7.3-2
unbound-control 1.7.3-2
unbound-control-setup 1.7.3-2

Firmware: OpenWrt 18.06.0 r7188-b0b5c64c22 / LuCI openwrt-18.06 branch (git-18.210.69179-6df9a57)

**Comment by dibdot** [comment]
If you like to use unbound utilities directly, you have to configure /etc/unbound/unbound.conf - and not the openwrt related uci unbound config in /etc/config/unbound, e.g. set the following options in /etc/unbound/unbound.conf:

```
# Remote control config section.
remote-control:
        # Enable remote control with unbound-control(8) here.
        # set up the keys and certificates with unbound-control-setup.
        control-enable: yes

        # Set to no and use an absolute path as control-interface to use
        # a unix local named pipe for unbound-control.
        control-use-cert: no
```
and `unbound-control status` will work, e.g.:

```
root@blackhole:/etc/unbound# unbound-control status
version: 1.7.3
verbosity: 1
threads: 4
modules: 2 [ validator iterator ]
uptime: 42304 seconds
options: control
unbound (pid 8774) is running...
```

@EricLuehrsen who knows best about. ;-)
