### ISSUE TITLE
unbound: silently skips TLS certificate validation

### ISSUE THREAD

**Issue by jorti** [openwrt/packages#6717]
Maintainer: @EricLuehrsen 
Environment: x86_64 KVM virtual machine, OpenWrt 18.06.0

Versions:
unbound - 1.7.3-2
libopenssl - 1.0.2o-1

Description:
Unbound silently skips TLS certificate validation. It continues to resolve happily after configuring it like this:

```
server:
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

forward-zone:
    name: "."
    forward-ssl-upstream: yes
    forward-addr: 1.1.1.1@853#bad-hostname.com
    forward-addr: 1.0.0.1@853#bad-hostname.com
```

In this upstream bug report can be seen that OpenSSL 1.1.x is needed for this feature to work.

https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=658#c15

If upgrading to OpenSSL 1.1.x is not yet possible, please, at least include the patch mentioned in that bug to warn the user that the name verification functionality is not available.
