### ISSUE TITLE
unbound: using DNS-over-TLS, ssl handshakes fail after a few days

### ISSUE THREAD

**Issue by zedinosaur** [openwrt/packages#6925]
Maintainer: @EricLuehrsen 
Environment: Linksys WRT1900ACSv1, mvebu arch, OpenWrt version: 18.06.1

Description:
I've configured unbound to use DNS-over-TLS for forwarding. Usually after the router has been up for a few days it starts failing to resolve, apparently failing the ssl handshake. Restarting it immediately solves the problem but it returns again after a few days.

log messages
```
Sat Sep  1 17:47:29 2018 daemon.notice unbound: [24512:0] notice: ssl handshake failed 1.0.0.1 port 853
Sat Sep  1 17:47:29 2018 daemon.err unbound: [24512:0] error: ssl handshake failed crypto error:07064041:lib(7):func(100):reason(65)
Sat Sep  1 17:47:29 2018 daemon.notice unbound: [24512:0] notice: ssl handshake failed 9.9.9.10 port 853
Sat Sep  1 17:47:29 2018 daemon.err unbound: [24512:0] error: ssl handshake failed crypto error:07064041:lib(7):func(100):reason(65)
Sat Sep  1 17:47:29 2018 daemon.notice unbound: [24512:0] notice: ssl handshake failed 9.9.9.10 port 853
Sat Sep  1 17:47:29 2018 daemon.err unbound: [24512:0] error: ssl handshake failed crypto error:07064041:lib(7):func(100):reason(65)
Sat Sep  1 17:47:29 2018 daemon.notice unbound: [24512:0] notice: ssl handshake failed 1.1.1.1 port 853
Sat Sep  1 17:47:29 2018 daemon.err unbound: [24512:0] error: ssl handshake failed crypto error:07064041:lib(7):func(100):reason(65)
```

unbound_ext.conf:
```
forward-zone:
  name: "."
  forward-addr: 1.1.1.1@853#cloudflare-dns.com
  forward-addr: 1.0.0.1@853#cloudflare-dns.com
  forward-addr: 9.9.9.10@853#dns-nosec.quad9.net
  forward-ssl-upstream: yes
```

unbound_srv.conf
```
do-tcp: yes
prefetch: yes
qname-minimisation: yes
rrset-roundrobin: yes
use-caps-for-id: yes
tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt" # For OpenWrt
```
